name: 'Terraform GitHub Actions'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.5

      - name: 'Terraform Format'
        run: terraform fmt -check

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Install tflint'
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

      - name: 'Run tflint'
        run: tflint

      # Optional: Add tfsec or other static analysis tools
      - name: 'Install tfsec'
        run: |
          wget -q https://github.com/aquasecurity/tfsec/releases/download/v0.58.9/tfsec-linux-amd64
          mv tfsec-linux-amd64 tfsec
          chmod +x tfsec

      - name: 'Run tfsec'
        run: ./tfsec .
