name: Automatic Versioning

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  auto-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for version calculation
          ref: ${{ github.event.pull_request.head.ref }} # Checkout the source branch of the PR

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /github/workspace

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          RELEASE_BRANCHES: main
